services:
  python:
    image: tyamadabiodataeng/pharmaomicspy
    platform: linux/amd64
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    command: /bin/bash
    volumes:
     - .:/usr/src/
    tty: true
    stdin_open: true
