[project]
name = "pharmaomicspy"
version = "0.1.0"
description = "A python library for a simplified and streamlined pharmaco-omics workflow."
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "scipy",
    "statsmodels",
    "matplotlib",
    "seaborn",
    "fastcluster",
    "openpyxl",
    "requests",
    "pandas[performance, plot, computation, excel, hdf5]",
    "polars-lts-cpu",
    "ibis-framework[pandas, polars]",
    "scikit-learn",
    "rdkit",
    "biopython",
    "anndata",
    "scanpy[leiden]",
]

[dependency-groups]
dev = [
    "black",
    "ruff",
    "mypy",
    "tox",
    "zensical",
    "pytest",
    "jupyterlab",
    "line_profiler",
    "memory_profiler",
]

[tool.tox]
legacy_tox_ini = """
    [tox]
    skipdist = True
    env_list = 
        black
        ruff
        mypy

    [black]
    deps = black
    commands = black .

    [ruff]
    deps = ruff
    commands = ruff check .

    [mypy]
    deps = mypy
    commands = mypy .
"""

[tool.ruff]
lint.ignore = ['E501']
lint.select = [
    'C9',  # mccabe
    'E',  # pycodestyle Error
    'F',  # PyFlakes
    'W',  # pycodestyle Warning
]
line-length = 120
src = ['.']

[tool.ruff.format]
quote-style = 'single'

[tool.pytest.ini_options]
python_files = ["test_*.py"]
testpaths = ["tests"]
pythonpath = ['src', 'tests']
norecursedirs = '.venv'
